In [1]:
import tensorflow as tf
import numpy as np

In [3]:
# 输入矩阵
M = np.array(
    [
        [[1], [-1], [0]],
        [[-1], [2], [1]],
        [[0], [2], [-2]]
    ]
)
print(M.shape)

(3, 3, 1)


In [5]:
# 定义卷积过滤器，深度为1
# 前两个维度代表了过滤器的尺寸，第三个维度表示当前层的深度，第四个维度表示过滤器的深度
filter_weight = tf.get_variable('weights', [2, 2, 1, 1], initializer=tf.constant_initializer([
    [1, -1],
    [0, 2]
]))
biases = tf.get_variable('biases', [1], initializer=tf.constant_initializer(1))

和卷积层的权重类似，当前层矩阵上不同位置的偏置项也是共享的，所以总共有下一层深度个不同的biases。

In [7]:
# 调整输入格式符合tensorflow的要求
M = np.array(M, dtype='float32')
M = M.reshape(1, 3, 3, 1)

In [8]:
# 计算矩阵通过卷积层过滤器和池化层过滤器计算后的结果
x = tf.placeholder('float32', [1, None, None, 1])
# tf.nn.conv2d提供了一个非常方便的函数来实现卷积层前向传播的算法
# 参数：当前层的节点矩阵；卷积层的权重；不同维度上的步长；填充的方法
conv = tf.nn.conv2d(x, filter_weight, strides=[1, 2, 2, 1], padding='SAME')
bias = tf.nn.bias_add(conv, biases)
# 池化层的过滤器还需要在深度这个维度上移动;ksize提供了过滤器的尺寸
pool = tf.nn.avg_pool(x, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    convoluted_M = sess.run(bias, feed_dict={x: M})
    pooled_M = sess.run(pool, feed_dict={x: M})
    print("convoluted_M:\n", convoluted_M)
    print("pooled_M:\n",pooled_M)

convoluted_M:
 [[[[ 7.]
   [ 1.]]

  [[-1.]
   [-1.]]]]
pooled_M:
 [[[[ 0.25]
   [ 0.5 ]]

  [[ 1.  ]
   [-2.  ]]]]
